import { createAction } from "redux-actions";

//USE ENUM TO DECLARE A GROUP FO CONST
export enum CategoriesActionTypes {
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR",
  GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID",
  GET_CATEGORY_BY_ID_SUCCESS = "GET_CATEGORY_BY_ID_SUCCESS",
  GET_CATEGORY_BY_ID_ERROR = "GET_CATEGORY_BY_ID_ERROR",
}

export const SET_SHOW_SPOTIFY_LOGO_BACK = "SET_SHOW_SPOTIFY_LOGO_BACK";
